apiVersion: app/v1
kind: Deployment
metadata:
   name: addressbook
   labels:
     app: addressbook
spec:
   replicas: 2
   selector:
     matchLabels:
        app: addressbook
   template:     
      metadata:
         name: pod_addressbook
         labels:
            app: addressbook
      spec:
         containers:
          - name: addressbook
            image: vigneshbalajiee/addressbook:19
            ports:
             - containerPort: 8080
         
