apiVersion: v1
kind: Service
metadata:
   name: addressbook-service
   labels:
      app: addressbook
spec:
   type: NodePort
   ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
   selector:
       app: addressbook