 groups:
     - name: docker_alerts
       rules:
         - alert: DockerContainerDown
           expr: absent(container_memory_usage_bytes{name="Reactapp"})
           for: 1m
           labels:
             severity: critical
           annotations:
             summary: "Docker container down"
             description: "Container {{ $labels.name }} is down for more than 1 minute."
